### PR TITLE
write to destination directly instead of temp dir folder

### LINKED ISSUE #25: unzipping to a partition other than `C:/` fails with OSError
On Windows, unzipping to a partition other than `C:/` fails.

When unzipping, you creating a temporary folder & are writing archive contents to that temporary folder, then moving contents to the final folder. However, [Nim currently has a bug where `moveDir` operations across partitions fail](https://github.com/nim-lang/Nim/issues/18216).

I would suggest either:
- waiting until the issue is fixed
- replacing [`moveDir(tempDir, dest)`](https://github.com/guzba/zippy/blob/a059310cb2348bd4b8b2573b6204af289b8cf16b/src/zippy/ziparchives.nim#L417) with a `copyDir` and `removeDir` operation
- write directly to the destination folder instead of using a temporary dir (is there a reason for that?)

### PR DESCRIPTION
**Pull request by froehlichA**
In ZipArchives, writes directly to destination instead of a temporary folder.

If the export fails during the process, the destination folder is deleted in order to not leave half finished exports (We're allowed to do that because we abort if the destination folder exists anyway, so no other files are getting deleted).

Fixes #25.

Difficult to write tests because issue only occurs on seperate partitions, but tested locally on both Windows and Linux.

### CODE REVIEW

**Comment by froehlichA** [comment]
I've completely removed the code that creates a temp folder now. Tell me if I'm missing something, but IMO we can just remove the destination folder if export fails.

**Comment by guzba** [comment]
Thanks for the PR. I haven't been able to look at this yet but I will as soon as I can. Should be back to normal and able to look at this in a couple days.

**Comment by froehlichA** [comment]
Have you been able to look at this yet?

**Comment by guzba** [comment]
Thanks for the PR!

**Pull request merged**
